version: '3.8'

services:
  app:
    image: node:18
    container_name: meeting-notes-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # ホストの node_modules を使わない
    ports:
      - "3000:3000"
    command: sh -c "npm install && sleep 3 && npm run dev"
