version: '3.8'

services:
  app:
    image: node:18
    container_name: meeting-notes-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
